apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-deployment
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
        - image: dhawal901/k8s_api:v1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: backend-config
          name: backend
          ports:
            - containerPort: 3001
          livenessProbe:
            httpGet:
              path: /health_check
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend-deployment
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30002

---

