apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  POSTGRES_USER: demo_user
  POSTGRES_PASSWORD: demo_user
  POSTGRES_DB: demo_db

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  CONNECTION_STRING: postgres://demo_user:demo_user@postgres-service/demo_db
  ORIGIN: http://localhost:30001
  PORT: "3001"

---

